import type { Metadata } from "next"
import { Manrope } from "next/font/google"
import "../globals.css"
import Body from "@/components/Layout/Body"
import "react-toastify/dist/ReactToastify.css"
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${manrope.variable} overflow-x-hidden`}>
      <Body>{children}</Body>
    </html>
  )
}
